### PR TITLE
Upgrade to 050

### PR DESCRIPTION
**Pull request by jvalenzu**
Modify the public sample to match internal 0.50 entities samples
Update Editor version to 2020.3.30f1 (1fb1bf06830e)

### CODE REVIEW

**Comment by jvalenzu** [comment]
Creating a new pull request because apparently my first push created a protected branch that I someone do not have permission to push to.

Old PR:
https://github.com/Unity-Technologies/EntityComponentSystemSamples/pull/204

**Comment by jvalenzu** [comment]
@BrianWill-Unity This push has URP and AFAIK works without error.  I'm not sure why you would have had to create any settings, all the relevant assets should be included.

image

**Review by BrianWill-Unity — APPROVED** [review]
I think I maybe had a global cache issue. Anyway, after a clean reset with this branch and flushing the Library, it now renders out of the box 👍 .

**Review by kjellander-unity — APPROVED** [review]
I don't think I'm a useful reviewer here but this LGTM

**Review by unitydavidlo — APPROVED** [review]

**Pull request merged**
