### PR TITLE
Update the projects to entities 1.0.0-exp.8

### PR DESCRIPTION
**Pull request by abdul-unity**
* Update the packages to `1.0.0-exp.8`
* Update the projects to use `2022.2.0b8`

### CODE REVIEW

**Review by Drealmer — CHANGES_REQUESTED** [review]
I cannot add my reviews in the code because the PR is so big that the github interface becomes unresponsive. I'll put them here instead. I'm only reviewing the core entities samples, the other packages should be reviewed by their respective teams.

- The package com.unity.ai.navigation has been added to the project, that doesn't look intentional.
- I don't think the blob asset samples have been updated, they should probably be removed for now. I'll check with Anne.
- The FixedTimestepSystemUpdate sample doesn't work but afaik this one is okay on the internal repo, we should figure this one out. I'll have a look.
- The VirtualMemory sample is pointless and should be deleted, Bryan gave his approval. It's my fault it hasn't been deleted yet, I forgot to do that in the internal repo. I'll fix it there, but please remove it from here already.

Thanks for handling this Abdul!

**Comment by josepmariapujol-unity** [comment]
I am reviewing on behalf of the Unity Physics team, PhysicsSamples.
1. The project opens without errors. 🟢 
2. The project builds and runs scenes. 🟢 
3. The project only has one warning in the animations scene tests in one of the authoring scripts 🟡 
4. I tried making pushes and a PR but I receive this message:
`ERROR: The `Unity-Technologies' organization has enabled or enforced SAML SSO. To access
this repository, you must use the HTTPS remote with a personal access token
or SSH with an SSH key and passphrase
that has been authorized for this organization. Visit
https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/ for more information.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
I will follow-up on my side but besides that everything is working.

**Review by diegoossa — APPROVED** [review]
Looks good to me! 👍🏻

**Review by julianunity — APPROVED** [review]

**Review by josepmariapujol-unity — APPROVED** [review]
On behalf of the physics team, PhysicsSamples LGTM

**Review by Drealmer — APPROVED** [review]

**Pull request merged**
